// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0HYTBPAtAf01c8muBHHUuAa7gYDuOT0',
    appId: '1:58674608106:web:6436d31d397086a17ea493',
    messagingSenderId: '58674608106',
    projectId: 'amir-chat-16dd2',
    authDomain: 'amir-chat-16dd2.firebaseapp.com',
    storageBucket: 'amir-chat-16dd2.appspot.com',
    measurementId: 'G-S08702PWT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YQOHVC8sP7ih0JlvHFTZ_Jw2M99x0mk',
    appId: '1:58674608106:android:8b6665f70759fef17ea493',
    messagingSenderId: '58674608106',
    projectId: 'amir-chat-16dd2',
    storageBucket: 'amir-chat-16dd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIWmfcc-ESiOTwsG9tDUZ4OENRHwvjEA',
    appId: '1:58674608106:ios:57362275452100827ea493',
    messagingSenderId: '58674608106',
    projectId: 'amir-chat-16dd2',
    storageBucket: 'amir-chat-16dd2.appspot.com',
    iosClientId: '58674608106-s0406qmukogunsa7344c9880m94kdi5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.amirChhatApp',
  );
}
